name: Generate Images

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 0 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: latest
          registry-url: 'https://npm.pkg.github.com'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Packages
        run: yarn install --immutable
      - name: Run Program
        run: npx gh-lang-stats
        env:
          TOKEN: ${{ secrets.TOKEN }}
          # MAX_CONCUR: 5
          # INPUT_FILE: "template.svg"
          # OUTPUT_FILE: "generated.svg"
      - name: Commit & Push
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: "Generated Images"
          empty: true
